"""Validation layer package for deterministic contract checks."""

from .benchmark_validator import (
	BenchmarkValidationError,
	assert_valid_benchmark_registry,
	assert_valid_snapshot_lineage,
	validate_benchmark_registry,
	validate_snapshot_lineage,
)
from .ess_validator import EssValidationError, assert_valid_ess_file, validate_ess_file
from .market_cap_validator import (
	MarketCapValidationError,
	assert_valid_market_cap_config,
	validate_market_cap_config,
)
from .intake_readiness_validator import (
	DEFAULT_INTAKE_DIRECTORIES,
	INTAKE_BLOCKED_REASON,
	INTAKE_OPERATOR_GUIDANCE,
	IntakeReadinessResult,
	validate_intake_readiness,
)
from .persistence_validator import (
	ArtifactPersistenceCheck,
	PersistenceValidationResult,
	validate_ess_stage_persistence,
)
from .provider_mapping_validator import (
	ProviderMappingValidationError,
	ProviderMappingValidationResult,
	assert_valid_fidelity_provider_mappings,
	validate_fidelity_provider_mappings,
)
from .replay_validator import (
	validate_analytical_universe_required_fields,
	validate_benchmark_mapping_scope_symbols,
	validate_benchmark_mapping_completeness,
	validate_empty_replay_outputs,
	validate_investable_vehicle_mapping_completeness,
	validate_orphaned_replay_metadata,
	validate_performance_series_shape,
	validate_replay_availability_consistency,
	validate_replay_ui_mismatch,
	validate_replay_no_lookahead,
	validate_top_n_selection_reproducibility,
	validate_unsupported_category_exposure,
	validate_vehicle_mapping_scope_symbols,
)
from .market_data_validator import (
	validate_benchmark_history_presence,
	validate_benchmark_return_rows,
	validate_historical_price_rows,
	validate_investable_vehicle_return_rows,
	validate_curve_depth,
	validate_historical_replay_window,
	validate_no_lookahead_series_dates,
	validate_price_coverage,
	validate_replay_window,
	validate_timeseries_monotonic_dates,
	validate_vehicle_history_presence,
)

__all__ = [
	"BenchmarkValidationError",
	"EssValidationError",
	"DEFAULT_INTAKE_DIRECTORIES",
	"INTAKE_BLOCKED_REASON",
	"INTAKE_OPERATOR_GUIDANCE",
	"MarketCapValidationError",
	"ArtifactPersistenceCheck",
	"PersistenceValidationResult",
	"IntakeReadinessResult",
	"ProviderMappingValidationError",
	"ProviderMappingValidationResult",
	"assert_valid_benchmark_registry",
	"assert_valid_ess_file",
	"assert_valid_fidelity_provider_mappings",
	"assert_valid_market_cap_config",
	"assert_valid_snapshot_lineage",
	"validate_benchmark_registry",
	"validate_ess_file",
	"validate_fidelity_provider_mappings",
	"validate_intake_readiness",
	"validate_ess_stage_persistence",
	"validate_benchmark_return_rows",
	"validate_benchmark_history_presence",
	"validate_curve_depth",
	"validate_historical_replay_window",
	"validate_historical_price_rows",
	"validate_investable_vehicle_return_rows",
	"validate_market_cap_config",
	"validate_no_lookahead_series_dates",
	"validate_price_coverage",
	"validate_analytical_universe_required_fields",
	"validate_benchmark_mapping_scope_symbols",
	"validate_benchmark_mapping_completeness",
	"validate_empty_replay_outputs",
	"validate_investable_vehicle_mapping_completeness",
	"validate_orphaned_replay_metadata",
	"validate_performance_series_shape",
	"validate_replay_availability_consistency",
	"validate_replay_ui_mismatch",
	"validate_replay_no_lookahead",
	"validate_replay_window",
	"validate_snapshot_lineage",
	"validate_timeseries_monotonic_dates",
	"validate_top_n_selection_reproducibility",
	"validate_unsupported_category_exposure",
	"validate_vehicle_mapping_scope_symbols",
	"validate_vehicle_history_presence",
]